<#
.SYNOPSIS
  Creates a single code-signing test certificate for the KMTO driver and
  writes the kmto_driver_signing.props file that MSBuild will consume.

.NOTES
  - The certificate is created under CurrentUser\My (no admin required).
  - To also add it to TrustedPublisher, re-run this script "As Administrator"
    (optional).
  - Test-signed drivers: bcdedit /set testsigning on, then reboot.
#>
$ErrorActionPreference = 'Stop'
$driverDir = $PSScriptRoot
$propsPath = Join-Path $driverDir 'kmto_driver_signing.props'
$subject = 'CN=KMTO Kernel Mode Test Signing'

Write-Host "Location: $driverDir"

$existing = Get-ChildItem Cert:\CurrentUser\My | Where-Object { $_.Subject -eq $subject }
if ($existing) {
    $cert = $existing[0]
    Write-Host "Using existing certificate: $($cert.Thumbprint)"
} else {
    $cert = New-SelfSignedCertificate `
        -Subject $subject `
        -CertStoreLocation 'Cert:\CurrentUser\My' `
        -Type CodeSigningCert `
        -HashAlgorithm SHA256 `
        -NotAfter (Get-Date).AddYears(10)
    Write-Host "New certificate created: $($cert.Thumbprint)"
}

$sha1 = $cert.Thumbprint

$xml = @"
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- This file is generated by Create-KmtoTestCertificate.ps1; it is not committed to git. -->
  <PropertyGroup>
    <TestCertificate>$sha1</TestCertificate>
  </PropertyGroup>
</Project>
"@
Set-Content -Path $propsPath -Value $xml -Encoding UTF8
Write-Host "Written: $propsPath"

$published = Get-ChildItem Cert:\LocalMachine\TrustedPublisher -ErrorAction SilentlyContinue | Where-Object { $_.Thumbprint -eq $sha1 }
if (-not $published) {
    try {
        $store = New-Object System.Security.Cryptography.X509Certificates.X509Store('TrustedPublisher', 'LocalMachine')
        $store.Open('ReadWrite')
        try {
            $store.Add($cert)
        } finally {
            $store.Close()
        }
        Write-Host "Certificate added to LocalMachine\TrustedPublisher store."
    } catch {
        Write-Warning "Could not add to TrustedPublisher (usually requires admin): $($_.Exception.Message)"
        Write-Host "If test-signing mode is on (bcdedit testsigning on), the driver can still load."
    }
} else {
    Write-Host "Certificate is already in TrustedPublisher."
}

Write-Host ""
Write-Host "Next steps:"
Write-Host "  1) bcdedit /set testsigning on"
Write-Host "  2) Reboot"
Write-Host "  3) Build the driver as Release|x64"
